<?php

declare(strict_types=1);

return [
    'types' => [
        'personal' => ['label' => 'Pessoal', 'description' => 'Um espaço pessoal ou página de apresentação.'],
        'portfolio' => ['label' => 'Portfólio', 'description' => 'Mostra trabalho, projetos e experiência.'],
        'business' => ['label' => 'Empresa', 'description' => 'Uma presença profissional para a tua empresa.'],
        'online_store' => ['label' => 'Loja online', 'description' => 'Produtos, catálogo e estrutura de ecommerce.'],
        'blog' => ['label' => 'Blog', 'description' => 'Conteúdo, artigos e publicação regular.'],
        'restaurant' => ['label' => 'Restaurante', 'description' => 'Menu, localização, reservas e contacto.'],
        'services' => ['label' => 'Serviços', 'description' => 'Apresenta serviços e capta contactos.'],
        'landing' => ['label' => 'Landing page', 'description' => 'Uma página focada numa oferta ou campanha.'],
        'agency' => ['label' => 'Agência', 'description' => 'Projetos, serviços, equipa e captação de clientes.'],
        'photographer' => ['label' => 'Fotógrafo', 'description' => 'Portfólio visual, galerias e pedidos de orçamento.'],
        'real_estate' => ['label' => 'Imobiliária', 'description' => 'Imóveis, serviços, contactos e pedidos de visita.'],
        'clinic' => ['label' => 'Clínica', 'description' => 'Serviços, equipa, informação e marcações.'],
        'lawyer' => ['label' => 'Advogado', 'description' => 'Áreas de prática, confiança, equipa e contacto.'],
        'gym' => ['label' => 'Ginásio', 'description' => 'Serviços, planos, equipa e inscrições.'],
        'beauty' => ['label' => 'Salão de beleza', 'description' => 'Serviços, galeria, preços e marcações.'],
        'hotel' => ['label' => 'Hotel', 'description' => 'Alojamento, comodidades, galeria e reservas.'],
        'cafe' => ['label' => 'Café', 'description' => 'Menu, ambiente, localização e contacto.'],
        'startup' => ['label' => 'Startup', 'description' => 'Produto, proposta de valor, equipa e conversão.'],
    ],

    'templates' => [
        'studio' => [
            'label' => 'Studio',
            'description' => 'Minimalista, editorial e focado no conteúdo.',
            'style' => 'Minimalista',
            'accent' => '#635bff',
        ],
        'launch' => [
            'label' => 'Launch',
            'description' => 'Moderno, energético e orientado para conversão.',
            'style' => 'Moderno',
            'accent' => '#2563eb',
        ],
        'commerce' => [
            'label' => 'Commerce',
            'description' => 'Organizado para produtos, catálogo e vendas.',
            'style' => 'Comercial',
            'accent' => '#059669',
        ],
        'elegant' => [
            'label' => 'Elegant',
            'description' => 'Premium, sofisticado e com bastante espaço visual.',
            'style' => 'Premium',
            'accent' => '#7c3aed',
        ],
        'professional' => [
            'label' => 'Professional',
            'description' => 'Corporativo, claro e orientado para confiança.',
            'style' => 'Profissional',
            'accent' => '#0f766e',
        ],
        'creative' => [
            'label' => 'Creative',
            'description' => 'Visual, expressivo e pensado para destacar projetos.',
            'style' => 'Criativo',
            'accent' => '#db2777',
        ],
    ],

    'pages' => [
        'home' => 'Home',
        'about' => 'Sobre',
        'services' => 'Serviços',
        'products' => 'Produtos',
        'blog' => 'Blog',
        'contact' => 'Contacto',
        'faq' => 'FAQ',
        'gallery' => 'Galeria',
        'pricing' => 'Preços',
        'team' => 'Equipa',
        'privacy' => 'Privacidade',
    ],

    'recommended_pages' => [
        'business' => ['home', 'about', 'services', 'contact'],
        'agency' => ['home', 'services', 'about', 'contact'],
        'restaurant' => ['home', 'about', 'gallery', 'contact'],
        'online_store' => ['home', 'products', 'about', 'contact'],
        'portfolio' => ['home', 'about', 'gallery', 'contact'],
        'photographer' => ['home', 'gallery', 'about', 'contact'],
        'real_estate' => ['home', 'products', 'about', 'contact'],
        'clinic' => ['home', 'services', 'about', 'contact'],
        'lawyer' => ['home', 'services', 'about', 'contact'],
        'gym' => ['home', 'services', 'pricing', 'contact'],
        'beauty' => ['home', 'services', 'gallery', 'contact'],
        'hotel' => ['home', 'gallery', 'about', 'contact'],
        'cafe' => ['home', 'about', 'gallery', 'contact'],
        'startup' => ['home', 'services', 'about', 'contact'],
        'services' => ['home', 'services', 'about', 'contact'],
        'landing' => ['home'],
        'personal' => ['home', 'about', 'contact'],
        'blog' => ['home', 'blog', 'about', 'contact'],
    ],

    /*
    |--------------------------------------------------------------------------
    | Conteúdo e navegação específicos de cada tipo de website
    |--------------------------------------------------------------------------
    |
    | O tipo do website é a fonte de verdade para o painel de gestão:
    | - campos que o proprietário deve preencher;
    | - categorias que aparecem na sidebar;
    | - destino de cada item da sidebar.
    |
    | Os valores preenchidos pelo utilizador são guardados em
    | sites.settings.model_content, por isso não é necessária uma tabela nova.
    |
    */
    'model_profiles' => [
        'personal' => [
            'label' => 'Website pessoal',
            'description' => 'Preenche os dados que melhor representam a tua identidade, experiência e presença profissional.',
            'icon' => 'user',
            'fields' => [
                ['key' => 'display_name', 'label' => 'Nome', 'placeholder' => 'Ex.: Eduardo Louro Patrício', 'type' => 'text', 'required' => true],
                ['key' => 'headline', 'label' => 'Título profissional', 'placeholder' => 'Ex.: Web Developer | Laravel & PHP', 'type' => 'text'],
                ['key' => 'bio', 'label' => 'Sobre mim', 'placeholder' => 'Escreve uma apresentação curta e profissional.', 'type' => 'textarea'],
                ['key' => 'experience', 'label' => 'Experiência', 'placeholder' => 'Experiência profissional, funções e principais resultados.', 'type' => 'textarea'],
                ['key' => 'education', 'label' => 'Formação', 'placeholder' => 'Cursos, licenciaturas, certificações e formação relevante.', 'type' => 'textarea'],
                ['key' => 'skills', 'label' => 'Competências', 'placeholder' => 'Ex.: Laravel, PHP, MySQL, JavaScript, Git...', 'type' => 'textarea'],
                ['key' => 'projects', 'label' => 'Projetos', 'placeholder' => 'Projetos, trabalhos ou casos que queres destacar.', 'type' => 'textarea'],
                ['key' => 'location', 'label' => 'Localização', 'placeholder' => 'Ex.: Lisboa, Portugal', 'type' => 'text'],
                ['key' => 'contact_email', 'label' => 'Email profissional', 'placeholder' => 'email@exemplo.pt', 'type' => 'email'],
            ],
            'sidebar' => [
                ['label' => 'Perfil', 'icon' => 'user', 'anchor' => 'model-profile'],
                ['label' => 'Sobre mim', 'icon' => 'sparkles', 'anchor' => 'model-bio'],
                ['label' => 'Experiência', 'icon' => 'briefcase', 'anchor' => 'model-experience'],
                ['label' => 'Formação', 'icon' => 'academic-cap', 'anchor' => 'model-education'],
                ['label' => 'Competências', 'icon' => 'bolt', 'anchor' => 'model-skills'],
                ['label' => 'Projetos', 'icon' => 'rocket-launch', 'anchor' => 'model-projects'],
                ['label' => 'Contacto', 'icon' => 'envelope', 'anchor' => 'model-contact'],
            ],
        ],
        'portfolio' => [
            'label' => 'Portfólio',
            'description' => 'Organiza a tua apresentação profissional e os projetos que queres mostrar.',
            'icon' => 'rectangle-group',
            'fields' => [
                ['key' => 'display_name', 'label' => 'Nome / Marca', 'placeholder' => 'Nome apresentado no portfólio', 'type' => 'text', 'required' => true],
                ['key' => 'headline', 'label' => 'Especialidade', 'placeholder' => 'Ex.: Product Designer & Creative Developer', 'type' => 'text'],
                ['key' => 'bio', 'label' => 'Apresentação', 'placeholder' => 'Resumo profissional.', 'type' => 'textarea'],
                ['key' => 'projects', 'label' => 'Projetos em destaque', 'placeholder' => 'Lista e descrição dos principais projetos.', 'type' => 'textarea'],
                ['key' => 'skills', 'label' => 'Competências', 'placeholder' => 'Ferramentas, tecnologias ou áreas de especialização.', 'type' => 'textarea'],
                ['key' => 'experience', 'label' => 'Experiência', 'placeholder' => 'Experiência e resultados relevantes.', 'type' => 'textarea'],
                ['key' => 'contact_email', 'label' => 'Email profissional', 'placeholder' => 'email@exemplo.pt', 'type' => 'email'],
            ],
            'sidebar' => [
                ['label' => 'Perfil', 'icon' => 'user', 'anchor' => 'model-profile'],
                ['label' => 'Projetos', 'icon' => 'rocket-launch', 'anchor' => 'model-projects'],
                ['label' => 'Competências', 'icon' => 'bolt', 'anchor' => 'model-skills'],
                ['label' => 'Experiência', 'icon' => 'briefcase', 'anchor' => 'model-experience'],
                ['label' => 'Contacto', 'icon' => 'envelope', 'anchor' => 'model-contact'],
            ],
        ],
        'business' => [
            'label' => 'Empresa',
            'description' => 'Dados essenciais para apresentar a empresa, os serviços e a proposta de valor.',
            'icon' => 'building-office-2',
            'fields' => [
                ['key' => 'company_name', 'label' => 'Nome da empresa', 'placeholder' => 'Nome comercial', 'type' => 'text', 'required' => true],
                ['key' => 'headline', 'label' => 'Proposta de valor', 'placeholder' => 'Em uma frase, o que fazes e para quem?', 'type' => 'text'],
                ['key' => 'about', 'label' => 'Sobre a empresa', 'placeholder' => 'História, posicionamento e diferenciação.', 'type' => 'textarea'],
                ['key' => 'services', 'label' => 'Serviços', 'placeholder' => 'Serviços e respetivas descrições.', 'type' => 'textarea'],
                ['key' => 'team', 'label' => 'Equipa', 'placeholder' => 'Pessoas, funções e especialidades.', 'type' => 'textarea'],
                ['key' => 'clients', 'label' => 'Clientes / setores', 'placeholder' => 'Clientes, setores ou tipos de projetos.', 'type' => 'textarea'],
                ['key' => 'location', 'label' => 'Localização', 'placeholder' => 'Morada ou área de atuação', 'type' => 'text'],
                ['key' => 'contact_email', 'label' => 'Email comercial', 'placeholder' => 'geral@empresa.pt', 'type' => 'email'],
            ],
            'sidebar' => [
                ['label' => 'Empresa', 'icon' => 'building-office-2', 'anchor' => 'model-profile'],
                ['label' => 'Sobre', 'icon' => 'information-circle', 'anchor' => 'model-about'],
                ['label' => 'Serviços', 'icon' => 'briefcase', 'anchor' => 'model-services'],
                ['label' => 'Equipa', 'icon' => 'users', 'anchor' => 'model-team'],
                ['label' => 'Clientes', 'icon' => 'building-storefront', 'anchor' => 'model-clients'],
                ['label' => 'Contacto', 'icon' => 'envelope', 'anchor' => 'model-contact'],
            ],
        ],
        'online_store' => [
            'label' => 'Loja online',
            'description' => 'Configuração orientada para catálogo, vendas, clientes e conversão.',
            'icon' => 'shopping-bag',
            'fields' => [
                ['key' => 'store_name', 'label' => 'Nome da loja', 'placeholder' => 'Nome da marca', 'type' => 'text', 'required' => true],
                ['key' => 'headline', 'label' => 'Mensagem principal', 'placeholder' => 'A proposta principal da loja.', 'type' => 'text'],
                ['key' => 'about', 'label' => 'Sobre a marca', 'placeholder' => 'História e posicionamento da marca.', 'type' => 'textarea'],
                ['key' => 'featured_products', 'label' => 'Produtos em destaque', 'placeholder' => 'Que produtos ou coleções queres destacar?', 'type' => 'textarea'],
                ['key' => 'shipping', 'label' => 'Envios e entregas', 'placeholder' => 'Prazos, zonas e condições de entrega.', 'type' => 'textarea'],
                ['key' => 'returns', 'label' => 'Trocas e devoluções', 'placeholder' => 'Política de trocas e devoluções.', 'type' => 'textarea'],
                ['key' => 'contact_email', 'label' => 'Email de apoio', 'placeholder' => 'apoio@loja.pt', 'type' => 'email'],
            ],
            'sidebar' => [
                ['label' => 'Loja', 'icon' => 'shopping-bag', 'route' => 'settings'],
                ['label' => 'Produtos', 'icon' => 'archive-box', 'route' => 'products'],
                ['label' => 'Categorias', 'icon' => 'tag', 'route' => 'categories'],
                ['label' => 'Encomendas', 'icon' => 'clipboard-document-list', 'route' => 'orders'],
                ['label' => 'Clientes', 'icon' => 'users', 'route' => 'users'],
                ['label' => 'Promoções', 'icon' => 'sparkles', 'route' => 'promotions'],
            ],
        ],
        'blog' => [
            'label' => 'Blog',
            'description' => 'Define a identidade editorial e a informação principal do teu blog.',
            'icon' => 'document-text',
            'fields' => [
                ['key' => 'blog_name', 'label' => 'Nome do blog', 'placeholder' => 'Nome do blog', 'type' => 'text', 'required' => true],
                ['key' => 'headline', 'label' => 'Tema / promessa editorial', 'placeholder' => 'O que o leitor encontra aqui?', 'type' => 'text'],
                ['key' => 'about', 'label' => 'Sobre o blog', 'placeholder' => 'Descrição editorial.', 'type' => 'textarea'],
                ['key' => 'authors', 'label' => 'Autores', 'placeholder' => 'Autores e respetivas áreas.', 'type' => 'textarea'],
                ['key' => 'topics', 'label' => 'Temas principais', 'placeholder' => 'Tecnologia, carreira, viagens...', 'type' => 'textarea'],
                ['key' => 'contact_email', 'label' => 'Email', 'placeholder' => 'contacto@blog.pt', 'type' => 'email'],
            ],
            'sidebar' => [
                ['label' => 'Identidade', 'icon' => 'document-text', 'anchor' => 'model-profile'],
                ['label' => 'Sobre', 'icon' => 'information-circle', 'anchor' => 'model-about'],
                ['label' => 'Temas', 'icon' => 'hashtag', 'anchor' => 'model-topics'],
                ['label' => 'Autores', 'icon' => 'users', 'anchor' => 'model-authors'],
                ['label' => 'Contacto', 'icon' => 'envelope', 'anchor' => 'model-contact'],
            ],
        ],
        'restaurant' => [
            'label' => 'Restaurante',
            'description' => 'Conteúdo focado no espaço, menu, experiência e reservas.',
            'icon' => 'cake',
            'fields' => [
                ['key' => 'restaurant_name', 'label' => 'Nome do restaurante', 'placeholder' => 'Nome do restaurante', 'type' => 'text', 'required' => true],
                ['key' => 'headline', 'label' => 'Mensagem principal', 'placeholder' => 'Ex.: Cozinha portuguesa contemporânea', 'type' => 'text'],
                ['key' => 'about', 'label' => 'Sobre o restaurante', 'placeholder' => 'História, conceito e ambiente.', 'type' => 'textarea'],
                ['key' => 'menu', 'label' => 'Menu / especialidades', 'placeholder' => 'Pratos, menus ou especialidades.', 'type' => 'textarea'],
                ['key' => 'hours', 'label' => 'Horário', 'placeholder' => 'Dias e horários de funcionamento.', 'type' => 'textarea'],
                ['key' => 'reservation_info', 'label' => 'Reservas', 'placeholder' => 'Como reservar e informações importantes.', 'type' => 'textarea'],
                ['key' => 'location', 'label' => 'Localização', 'placeholder' => 'Morada do restaurante', 'type' => 'text'],
                ['key' => 'contact_email', 'label' => 'Email', 'placeholder' => 'reservas@restaurante.pt', 'type' => 'email'],
            ],
            'sidebar' => [
                ['label' => 'Restaurante', 'icon' => 'cake', 'anchor' => 'model-profile'],
                ['label' => 'Sobre', 'icon' => 'information-circle', 'anchor' => 'model-about'],
                ['label' => 'Menu', 'icon' => 'clipboard-document-list', 'anchor' => 'model-menu'],
                ['label' => 'Horários', 'icon' => 'clock', 'anchor' => 'model-hours'],
                ['label' => 'Reservas', 'icon' => 'calendar-days', 'anchor' => 'model-reservation'],
                ['label' => 'Contacto', 'icon' => 'map-pin', 'anchor' => 'model-contact'],
            ],
        ],
        'services' => [
            'label' => 'Serviços',
            'description' => 'Apresenta claramente os serviços, especialidades e forma de contacto.',
            'icon' => 'briefcase',
            'fields' => [
                ['key' => 'business_name', 'label' => 'Nome', 'placeholder' => 'Nome profissional ou da empresa', 'type' => 'text', 'required' => true],
                ['key' => 'headline', 'label' => 'Proposta de valor', 'placeholder' => 'O principal benefício que ofereces.', 'type' => 'text'],
                ['key' => 'about', 'label' => 'Sobre', 'placeholder' => 'Apresentação e experiência.', 'type' => 'textarea'],
                ['key' => 'services', 'label' => 'Serviços', 'placeholder' => 'Lista e descrição dos serviços.', 'type' => 'textarea'],
                ['key' => 'process', 'label' => 'Como funciona', 'placeholder' => 'Explica o processo de trabalho.', 'type' => 'textarea'],
                ['key' => 'faq', 'label' => 'Perguntas frequentes', 'placeholder' => 'Perguntas e respostas mais importantes.', 'type' => 'textarea'],
                ['key' => 'contact_email', 'label' => 'Email', 'placeholder' => 'contacto@exemplo.pt', 'type' => 'email'],
            ],
            'sidebar' => [
                ['label' => 'Perfil', 'icon' => 'user', 'anchor' => 'model-profile'],
                ['label' => 'Sobre', 'icon' => 'information-circle', 'anchor' => 'model-about'],
                ['label' => 'Serviços', 'icon' => 'briefcase', 'anchor' => 'model-services'],
                ['label' => 'Processo', 'icon' => 'list-bullet', 'anchor' => 'model-process'],
                ['label' => 'FAQ', 'icon' => 'question-mark-circle', 'anchor' => 'model-faq'],
                ['label' => 'Contacto', 'icon' => 'envelope', 'anchor' => 'model-contact'],
            ],
        ],
        'landing' => [
            'label' => 'Landing page',
            'description' => 'Foco numa oferta, produto, campanha ou conversão específica.',
            'icon' => 'cursor-arrow-rays',
            'fields' => [
                ['key' => 'headline', 'label' => 'Título principal', 'placeholder' => 'A mensagem que deve captar a atenção.', 'type' => 'text', 'required' => true],
                ['key' => 'subheadline', 'label' => 'Subtítulo', 'placeholder' => 'Explica rapidamente a oferta.', 'type' => 'textarea'],
                ['key' => 'offer', 'label' => 'Oferta', 'placeholder' => 'O que estás a oferecer?', 'type' => 'textarea'],
                ['key' => 'benefits', 'label' => 'Benefícios', 'placeholder' => 'Principais benefícios para o visitante.', 'type' => 'textarea'],
                ['key' => 'social_proof', 'label' => 'Prova social', 'placeholder' => 'Clientes, resultados, testemunhos ou números.', 'type' => 'textarea'],
                ['key' => 'cta', 'label' => 'Call to action', 'placeholder' => 'Ex.: Pedir demonstração', 'type' => 'text'],
                ['key' => 'contact_email', 'label' => 'Email', 'placeholder' => 'contacto@exemplo.pt', 'type' => 'email'],
            ],
            'sidebar' => [
                ['label' => 'Oferta', 'icon' => 'sparkles', 'anchor' => 'model-profile'],
                ['label' => 'Benefícios', 'icon' => 'check-badge', 'anchor' => 'model-benefits'],
                ['label' => 'Prova social', 'icon' => 'star', 'anchor' => 'model-social-proof'],
                ['label' => 'CTA', 'icon' => 'cursor-arrow-rays', 'anchor' => 'model-cta'],
                ['label' => 'Contacto', 'icon' => 'envelope', 'anchor' => 'model-contact'],
            ],
        ],
        'agency' => [
            'label' => 'Agência',
            'description' => 'Estrutura para apresentar equipa, serviços, projetos e captação de clientes.',
            'icon' => 'building-office',
            'fields' => [
                ['key' => 'agency_name', 'label' => 'Nome da agência', 'placeholder' => 'Nome da agência', 'type' => 'text', 'required' => true],
                ['key' => 'headline', 'label' => 'Posicionamento', 'placeholder' => 'O que torna a agência diferente?', 'type' => 'text'],
                ['key' => 'about', 'label' => 'Sobre', 'placeholder' => 'História e posicionamento.', 'type' => 'textarea'],
                ['key' => 'services', 'label' => 'Serviços', 'placeholder' => 'Áreas e serviços da agência.', 'type' => 'textarea'],
                ['key' => 'projects', 'label' => 'Projetos / casos', 'placeholder' => 'Projetos e resultados.', 'type' => 'textarea'],
                ['key' => 'team', 'label' => 'Equipa', 'placeholder' => 'Elementos e especialidades.', 'type' => 'textarea'],
                ['key' => 'contact_email', 'label' => 'Email comercial', 'placeholder' => 'hello@agencia.pt', 'type' => 'email'],
            ],
            'sidebar' => [
                ['label' => 'Agência', 'icon' => 'building-office', 'anchor' => 'model-profile'],
                ['label' => 'Sobre', 'icon' => 'information-circle', 'anchor' => 'model-about'],
                ['label' => 'Serviços', 'icon' => 'briefcase', 'anchor' => 'model-services'],
                ['label' => 'Projetos', 'icon' => 'rocket-launch', 'anchor' => 'model-projects'],
                ['label' => 'Equipa', 'icon' => 'users', 'anchor' => 'model-team'],
                ['label' => 'Contacto', 'icon' => 'envelope', 'anchor' => 'model-contact'],
            ],
        ],
        'photographer' => [
            'label' => 'Fotógrafo',
            'description' => 'Portfólio visual, serviços, especialidades e pedidos de orçamento.',
            'icon' => 'camera',
            'fields' => [
                ['key' => 'display_name', 'label' => 'Nome / marca', 'placeholder' => 'Nome do fotógrafo', 'type' => 'text', 'required' => true],
                ['key' => 'headline', 'label' => 'Especialidade', 'placeholder' => 'Ex.: Fotografia de casamento e retrato', 'type' => 'text'],
                ['key' => 'bio', 'label' => 'Sobre', 'placeholder' => 'Apresentação e estilo.', 'type' => 'textarea'],
                ['key' => 'services', 'label' => 'Serviços', 'placeholder' => 'Sessões, eventos, casamento, produto...', 'type' => 'textarea'],
                ['key' => 'portfolio', 'label' => 'Portfólio', 'placeholder' => 'Projetos, galerias ou trabalhos em destaque.', 'type' => 'textarea'],
                ['key' => 'pricing', 'label' => 'Preços / pacotes', 'placeholder' => 'Pacotes e informações comerciais.', 'type' => 'textarea'],
                ['key' => 'contact_email', 'label' => 'Email', 'placeholder' => 'hello@fotografo.pt', 'type' => 'email'],
            ],
            'sidebar' => [
                ['label' => 'Perfil', 'icon' => 'camera', 'anchor' => 'model-profile'],
                ['label' => 'Sobre', 'icon' => 'information-circle', 'anchor' => 'model-about'],
                ['label' => 'Portfólio', 'icon' => 'photo', 'anchor' => 'model-portfolio'],
                ['label' => 'Serviços', 'icon' => 'briefcase', 'anchor' => 'model-services'],
                ['label' => 'Preços', 'icon' => 'currency-euro', 'anchor' => 'model-pricing'],
                ['label' => 'Contacto', 'icon' => 'envelope', 'anchor' => 'model-contact'],
            ],
        ],
        'real_estate' => [
            'label' => 'Imobiliária',
            'description' => 'Apresenta imóveis, serviços, equipa e pedidos de visita.',
            'icon' => 'home-modern',
            'fields' => [
                ['key' => 'agency_name', 'label' => 'Nome da imobiliária', 'placeholder' => 'Nome comercial', 'type' => 'text', 'required' => true],
                ['key' => 'headline', 'label' => 'Mensagem principal', 'placeholder' => 'Ex.: Encontra a casa certa para a tua próxima fase.', 'type' => 'text'],
                ['key' => 'about', 'label' => 'Sobre', 'placeholder' => 'Experiência e posicionamento.', 'type' => 'textarea'],
                ['key' => 'properties', 'label' => 'Imóveis em destaque', 'placeholder' => 'Imóveis ou tipos de imóveis que queres destacar.', 'type' => 'textarea'],
                ['key' => 'services', 'label' => 'Serviços', 'placeholder' => 'Compra, venda, arrendamento, avaliação...', 'type' => 'textarea'],
                ['key' => 'team', 'label' => 'Equipa', 'placeholder' => 'Consultores e respetivas áreas.', 'type' => 'textarea'],
                ['key' => 'location', 'label' => 'Zona de atuação', 'placeholder' => 'Concelhos, cidades ou regiões.', 'type' => 'text'],
                ['key' => 'contact_email', 'label' => 'Email', 'placeholder' => 'geral@imobiliaria.pt', 'type' => 'email'],
            ],
            'sidebar' => [
                ['label' => 'Imobiliária', 'icon' => 'home-modern', 'anchor' => 'model-profile'],
                ['label' => 'Imóveis', 'icon' => 'building-office-2', 'anchor' => 'model-properties'],
                ['label' => 'Serviços', 'icon' => 'briefcase', 'anchor' => 'model-services'],
                ['label' => 'Equipa', 'icon' => 'users', 'anchor' => 'model-team'],
                ['label' => 'Zona de atuação', 'icon' => 'map-pin', 'anchor' => 'model-location'],
                ['label' => 'Contacto', 'icon' => 'envelope', 'anchor' => 'model-contact'],
            ],
        ],
        'clinic' => [
            'label' => 'Clínica',
            'description' => 'Informação clínica, serviços, equipa, localização e marcações.',
            'icon' => 'heart',
            'fields' => [
                ['key' => 'clinic_name', 'label' => 'Nome da clínica', 'placeholder' => 'Nome da clínica', 'type' => 'text', 'required' => true],
                ['key' => 'headline', 'label' => 'Mensagem principal', 'placeholder' => 'Proposta de valor da clínica.', 'type' => 'text'],
                ['key' => 'about', 'label' => 'Sobre', 'placeholder' => 'Apresentação da clínica.', 'type' => 'textarea'],
                ['key' => 'services', 'label' => 'Especialidades / serviços', 'placeholder' => 'Especialidades e serviços disponíveis.', 'type' => 'textarea'],
                ['key' => 'team', 'label' => 'Profissionais', 'placeholder' => 'Equipa, especialidades e qualificações.', 'type' => 'textarea'],
                ['key' => 'appointments', 'label' => 'Marcações', 'placeholder' => 'Como marcar e informações importantes.', 'type' => 'textarea'],
                ['key' => 'location', 'label' => 'Localização', 'placeholder' => 'Morada da clínica', 'type' => 'text'],
                ['key' => 'contact_email', 'label' => 'Email', 'placeholder' => 'geral@clinica.pt', 'type' => 'email'],
            ],
            'sidebar' => [
                ['label' => 'Clínica', 'icon' => 'heart', 'anchor' => 'model-profile'],
                ['label' => 'Serviços', 'icon' => 'briefcase', 'anchor' => 'model-services'],
                ['label' => 'Profissionais', 'icon' => 'users', 'anchor' => 'model-team'],
                ['label' => 'Marcações', 'icon' => 'calendar-days', 'anchor' => 'model-appointments'],
                ['label' => 'Localização', 'icon' => 'map-pin', 'anchor' => 'model-location'],
                ['label' => 'Contacto', 'icon' => 'envelope', 'anchor' => 'model-contact'],
            ],
        ],
        'lawyer' => [
            'label' => 'Advogado',
            'description' => 'Áreas de prática, apresentação profissional, equipa e contacto.',
            'icon' => 'scale',
            'fields' => [
                ['key' => 'display_name', 'label' => 'Nome', 'placeholder' => 'Nome do advogado / escritório', 'type' => 'text', 'required' => true],
                ['key' => 'headline', 'label' => 'Especialização', 'placeholder' => 'Áreas de prática principais.', 'type' => 'text'],
                ['key' => 'about', 'label' => 'Sobre', 'placeholder' => 'Experiência e abordagem.', 'type' => 'textarea'],
                ['key' => 'practice_areas', 'label' => 'Áreas de prática', 'placeholder' => 'Direito laboral, civil, comercial...', 'type' => 'textarea'],
                ['key' => 'team', 'label' => 'Equipa', 'placeholder' => 'Advogados e especialidades.', 'type' => 'textarea'],
                ['key' => 'faq', 'label' => 'Perguntas frequentes', 'placeholder' => 'Perguntas frequentes de clientes.', 'type' => 'textarea'],
                ['key' => 'contact_email', 'label' => 'Email', 'placeholder' => 'geral@escritorio.pt', 'type' => 'email'],
            ],
            'sidebar' => [
                ['label' => 'Perfil', 'icon' => 'scale', 'anchor' => 'model-profile'],
                ['label' => 'Sobre', 'icon' => 'information-circle', 'anchor' => 'model-about'],
                ['label' => 'Áreas de prática', 'icon' => 'briefcase', 'anchor' => 'model-practice-areas'],
                ['label' => 'Equipa', 'icon' => 'users', 'anchor' => 'model-team'],
                ['label' => 'FAQ', 'icon' => 'question-mark-circle', 'anchor' => 'model-faq'],
                ['label' => 'Contacto', 'icon' => 'envelope', 'anchor' => 'model-contact'],
            ],
        ],
        'gym' => [
            'label' => 'Ginásio',
            'description' => 'Serviços, planos, equipa, horários e inscrições.',
            'icon' => 'bolt',
            'fields' => [
                ['key' => 'gym_name', 'label' => 'Nome do ginásio', 'placeholder' => 'Nome do ginásio', 'type' => 'text', 'required' => true],
                ['key' => 'headline', 'label' => 'Mensagem principal', 'placeholder' => 'Motiva e explica a proposta do ginásio.', 'type' => 'text'],
                ['key' => 'about', 'label' => 'Sobre', 'placeholder' => 'Conceito e comunidade.', 'type' => 'textarea'],
                ['key' => 'services', 'label' => 'Serviços / aulas', 'placeholder' => 'Aulas, PT, modalidades e serviços.', 'type' => 'textarea'],
                ['key' => 'plans', 'label' => 'Planos', 'placeholder' => 'Mensalidades e o que inclui cada plano.', 'type' => 'textarea'],
                ['key' => 'schedule', 'label' => 'Horários', 'placeholder' => 'Horários do ginásio e aulas.', 'type' => 'textarea'],
                ['key' => 'contact_email', 'label' => 'Email', 'placeholder' => 'hello@ginasio.pt', 'type' => 'email'],
            ],
            'sidebar' => [
                ['label' => 'Ginásio', 'icon' => 'bolt', 'anchor' => 'model-profile'],
                ['label' => 'Serviços', 'icon' => 'briefcase', 'anchor' => 'model-services'],
                ['label' => 'Planos', 'icon' => 'credit-card', 'anchor' => 'model-plans'],
                ['label' => 'Horários', 'icon' => 'clock', 'anchor' => 'model-schedule'],
                ['label' => 'Equipa', 'icon' => 'users', 'anchor' => 'model-team'],
                ['label' => 'Contacto', 'icon' => 'envelope', 'anchor' => 'model-contact'],
            ],
        ],
        'beauty' => [
            'label' => 'Salão de beleza',
            'description' => 'Serviços, preços, galeria, equipa e marcações.',
            'icon' => 'sparkles',
            'fields' => [
                ['key' => 'salon_name', 'label' => 'Nome do salão', 'placeholder' => 'Nome do salão', 'type' => 'text', 'required' => true],
                ['key' => 'headline', 'label' => 'Mensagem principal', 'placeholder' => 'O conceito e experiência do salão.', 'type' => 'text'],
                ['key' => 'about', 'label' => 'Sobre', 'placeholder' => 'Apresentação do espaço.', 'type' => 'textarea'],
                ['key' => 'services', 'label' => 'Serviços', 'placeholder' => 'Cabelo, unhas, estética...', 'type' => 'textarea'],
                ['key' => 'pricing', 'label' => 'Preços', 'placeholder' => 'Serviços e preços.', 'type' => 'textarea'],
                ['key' => 'appointments', 'label' => 'Marcações', 'placeholder' => 'Como marcar.', 'type' => 'textarea'],
                ['key' => 'contact_email', 'label' => 'Email', 'placeholder' => 'hello@salao.pt', 'type' => 'email'],
            ],
            'sidebar' => [
                ['label' => 'Salão', 'icon' => 'sparkles', 'anchor' => 'model-profile'],
                ['label' => 'Serviços', 'icon' => 'briefcase', 'anchor' => 'model-services'],
                ['label' => 'Preços', 'icon' => 'currency-euro', 'anchor' => 'model-pricing'],
                ['label' => 'Galeria', 'icon' => 'photo', 'anchor' => 'model-gallery'],
                ['label' => 'Marcações', 'icon' => 'calendar-days', 'anchor' => 'model-appointments'],
                ['label' => 'Contacto', 'icon' => 'envelope', 'anchor' => 'model-contact'],
            ],
        ],
        'hotel' => [
            'label' => 'Hotel',
            'description' => 'Alojamento, comodidades, galeria, localização e reservas.',
            'icon' => 'building-office-2',
            'fields' => [
                ['key' => 'hotel_name', 'label' => 'Nome do hotel', 'placeholder' => 'Nome do hotel', 'type' => 'text', 'required' => true],
                ['key' => 'headline', 'label' => 'Mensagem principal', 'placeholder' => 'A experiência que o hotel oferece.', 'type' => 'text'],
                ['key' => 'about', 'label' => 'Sobre o hotel', 'placeholder' => 'História e conceito.', 'type' => 'textarea'],
                ['key' => 'rooms', 'label' => 'Quartos / alojamento', 'placeholder' => 'Tipos de quarto e características.', 'type' => 'textarea'],
                ['key' => 'amenities', 'label' => 'Comodidades', 'placeholder' => 'Piscina, spa, restaurante...', 'type' => 'textarea'],
                ['key' => 'reservations', 'label' => 'Reservas', 'placeholder' => 'Como reservar.', 'type' => 'textarea'],
                ['key' => 'location', 'label' => 'Localização', 'placeholder' => 'Morada do hotel', 'type' => 'text'],
                ['key' => 'contact_email', 'label' => 'Email', 'placeholder' => 'reservas@hotel.pt', 'type' => 'email'],
            ],
            'sidebar' => [
                ['label' => 'Hotel', 'icon' => 'building-office-2', 'anchor' => 'model-profile'],
                ['label' => 'Alojamento', 'icon' => 'home-modern', 'anchor' => 'model-rooms'],
                ['label' => 'Comodidades', 'icon' => 'sparkles', 'anchor' => 'model-amenities'],
                ['label' => 'Reservas', 'icon' => 'calendar-days', 'anchor' => 'model-reservations'],
                ['label' => 'Localização', 'icon' => 'map-pin', 'anchor' => 'model-location'],
                ['label' => 'Contacto', 'icon' => 'envelope', 'anchor' => 'model-contact'],
            ],
        ],
        'cafe' => [
            'label' => 'Café',
            'description' => 'Menu, ambiente, horários, localização e contacto.',
            'icon' => 'cake',
            'fields' => [
                ['key' => 'cafe_name', 'label' => 'Nome do café', 'placeholder' => 'Nome do café', 'type' => 'text', 'required' => true],
                ['key' => 'headline', 'label' => 'Mensagem principal', 'placeholder' => 'O que torna o café especial?', 'type' => 'text'],
                ['key' => 'about', 'label' => 'Sobre', 'placeholder' => 'História e ambiente.', 'type' => 'textarea'],
                ['key' => 'menu', 'label' => 'Menu', 'placeholder' => 'Bebidas, comida e especialidades.', 'type' => 'textarea'],
                ['key' => 'hours', 'label' => 'Horário', 'placeholder' => 'Dias e horários.', 'type' => 'textarea'],
                ['key' => 'location', 'label' => 'Localização', 'placeholder' => 'Morada', 'type' => 'text'],
                ['key' => 'contact_email', 'label' => 'Email', 'placeholder' => 'hello@cafe.pt', 'type' => 'email'],
            ],
            'sidebar' => [
                ['label' => 'Café', 'icon' => 'cake', 'anchor' => 'model-profile'],
                ['label' => 'Sobre', 'icon' => 'information-circle', 'anchor' => 'model-about'],
                ['label' => 'Menu', 'icon' => 'clipboard-document-list', 'anchor' => 'model-menu'],
                ['label' => 'Horário', 'icon' => 'clock', 'anchor' => 'model-hours'],
                ['label' => 'Localização', 'icon' => 'map-pin', 'anchor' => 'model-location'],
                ['label' => 'Contacto', 'icon' => 'envelope', 'anchor' => 'model-contact'],
            ],
        ],
        'startup' => [
            'label' => 'Startup',
            'description' => 'Produto, proposta de valor, equipa, tração e conversão.',
            'icon' => 'rocket-launch',
            'fields' => [
                ['key' => 'company_name', 'label' => 'Nome da startup', 'placeholder' => 'Nome da startup', 'type' => 'text', 'required' => true],
                ['key' => 'headline', 'label' => 'Proposta de valor', 'placeholder' => 'Que problema resolves e para quem?', 'type' => 'text'],
                ['key' => 'product', 'label' => 'Produto', 'placeholder' => 'Explica o produto ou solução.', 'type' => 'textarea'],
                ['key' => 'benefits', 'label' => 'Benefícios', 'placeholder' => 'Principais vantagens.', 'type' => 'textarea'],
                ['key' => 'traction', 'label' => 'Tração / resultados', 'placeholder' => 'Métricas e resultados que podes divulgar.', 'type' => 'textarea'],
                ['key' => 'team', 'label' => 'Equipa', 'placeholder' => 'Fundadores e equipa.', 'type' => 'textarea'],
                ['key' => 'contact_email', 'label' => 'Email', 'placeholder' => 'hello@startup.pt', 'type' => 'email'],
            ],
            'sidebar' => [
                ['label' => 'Startup', 'icon' => 'rocket-launch', 'anchor' => 'model-profile'],
                ['label' => 'Produto', 'icon' => 'cube', 'anchor' => 'model-product'],
                ['label' => 'Benefícios', 'icon' => 'check-badge', 'anchor' => 'model-benefits'],
                ['label' => 'Tração', 'icon' => 'chart-bar', 'anchor' => 'model-traction'],
                ['label' => 'Equipa', 'icon' => 'users', 'anchor' => 'model-team'],
                ['label' => 'Contacto', 'icon' => 'envelope', 'anchor' => 'model-contact'],
            ],
        ],
    ],
];
