<?php

declare(strict_types=1);

return [
    'types' => [
        'personal' => ['label' => 'Pessoal', 'description' => 'Um espaço pessoal ou página de apresentação.'],
        'portfolio' => ['label' => 'Portfólio', 'description' => 'Mostra trabalho, projetos e experiência.'],
        'business' => ['label' => 'Empresa', 'description' => 'Uma presença profissional para a tua empresa.'],
        'online_store' => ['label' => 'Loja online', 'description' => 'Produtos, catálogo e estrutura de ecommerce.'],
        'blog' => ['label' => 'Blog', 'description' => 'Conteúdo, artigos e publicação regular.'],
        'restaurant' => ['label' => 'Restaurante', 'description' => 'Menu, localização, reservas e contacto.'],
        'services' => ['label' => 'Serviços', 'description' => 'Apresenta serviços e capta contactos.'],
        'landing' => ['label' => 'Landing page', 'description' => 'Uma página focada numa oferta ou campanha.'],
        'agency' => ['label' => 'Agência', 'description' => 'Projetos, serviços, equipa e captação de clientes.'],
        'photographer' => ['label' => 'Fotógrafo', 'description' => 'Portfólio visual, galerias e pedidos de orçamento.'],
        'real_estate' => ['label' => 'Imobiliária', 'description' => 'Imóveis, serviços, contactos e pedidos de visita.'],
        'clinic' => ['label' => 'Clínica', 'description' => 'Serviços, equipa, informação e marcações.'],
        'lawyer' => ['label' => 'Advogado', 'description' => 'Áreas de prática, confiança, equipa e contacto.'],
        'gym' => ['label' => 'Ginásio', 'description' => 'Serviços, planos, equipa e inscrições.'],
        'beauty' => ['label' => 'Salão de beleza', 'description' => 'Serviços, galeria, preços e marcações.'],
        'hotel' => ['label' => 'Hotel', 'description' => 'Alojamento, comodidades, galeria e reservas.'],
        'cafe' => ['label' => 'Café', 'description' => 'Menu, ambiente, localização e contacto.'],
        'startup' => ['label' => 'Startup', 'description' => 'Produto, proposta de valor, equipa e conversão.'],
    ],

    'templates' => [
        'studio' => [
            'label' => 'Studio',
            'description' => 'Minimalista, editorial e focado no conteúdo.',
            'style' => 'Minimalista',
            'accent' => '#635bff',
        ],
        'launch' => [
            'label' => 'Launch',
            'description' => 'Moderno, energético e orientado para conversão.',
            'style' => 'Moderno',
            'accent' => '#2563eb',
        ],
        'commerce' => [
            'label' => 'Commerce',
            'description' => 'Organizado para produtos, catálogo e vendas.',
            'style' => 'Comercial',
            'accent' => '#059669',
        ],
        'elegant' => [
            'label' => 'Elegant',
            'description' => 'Premium, sofisticado e com bastante espaço visual.',
            'style' => 'Premium',
            'accent' => '#7c3aed',
        ],
        'professional' => [
            'label' => 'Professional',
            'description' => 'Corporativo, claro e orientado para confiança.',
            'style' => 'Profissional',
            'accent' => '#0f766e',
        ],
        'creative' => [
            'label' => 'Creative',
            'description' => 'Visual, expressivo e pensado para destacar projetos.',
            'style' => 'Criativo',
            'accent' => '#db2777',
        ],
    ],

    'pages' => [
        'home' => 'Home',
        'about' => 'Sobre',
        'services' => 'Serviços',
        'products' => 'Produtos',
        'blog' => 'Blog',
        'contact' => 'Contacto',
        'faq' => 'FAQ',
        'gallery' => 'Galeria',
        'pricing' => 'Preços',
        'team' => 'Equipa',
        'privacy' => 'Privacidade',
    ],

    'recommended_pages' => [
        'business' => ['home', 'about', 'services', 'contact'],
        'agency' => ['home', 'services', 'about', 'contact'],
        'restaurant' => ['home', 'about', 'gallery', 'contact'],
        'online_store' => ['home', 'products', 'about', 'contact'],
        'portfolio' => ['home', 'about', 'gallery', 'contact'],
        'photographer' => ['home', 'gallery', 'about', 'contact'],
        'real_estate' => ['home', 'products', 'about', 'contact'],
        'clinic' => ['home', 'services', 'about', 'contact'],
        'lawyer' => ['home', 'services', 'about', 'contact'],
        'gym' => ['home', 'services', 'pricing', 'contact'],
        'beauty' => ['home', 'services', 'gallery', 'contact'],
        'hotel' => ['home', 'gallery', 'about', 'contact'],
        'cafe' => ['home', 'about', 'gallery', 'contact'],
        'startup' => ['home', 'services', 'about', 'contact'],
        'services' => ['home', 'services', 'about', 'contact'],
        'landing' => ['home'],
        'personal' => ['home', 'about', 'contact'],
        'blog' => ['home', 'blog', 'about', 'contact'],
    ],
];
