            </div>
        </main>

        <aside class="builder-scroll hidden w-80 shrink-0 overflow-y-auto border-l border-zinc-200 bg-white lg:block dark:border-zinc-800 dark:bg-zinc-900">
            <div class="border-b border-zinc-100 p-4 dark:border-zinc-800"><p class="text-[10px] font-black uppercase tracking-widest text-indigo-600">3 · Personalizar</p><h2 class="mt-1 font-black">{{ $sections[$this->selectedSection ?? 0]['label'] ?? 'Elemento seleccionado' }}</h2><p class="mt-1 text-xs leading-5 text-zinc-500">Altera o conteúdo aqui ou edita directamente no website.</p></div>
            <div class="space-y-6 p-4">
                @if(isset($sections[0]))
                    @php($sIndex=$this->selectedSection ?? 0)
                    @if(isset($sections[$sIndex]))
                        @php($s=$sections[$sIndex])
                        @php($c=$s['content']??[])
                        <div><label class="text-xs font-bold">Nome interno</label><input wire:model.live="sections.{{ $sIndex }}.label" class="mt-2 w-full rounded-xl border-zinc-200 text-sm dark:border-zinc-700 dark:bg-zinc-800"></div>
                        @foreach(['title'=>'Título','subtitle'=>'Subtítulo','body'=>'Texto','description'=>'Descrição','button_label'=>'Texto do botão','button_url'=>'Ligação / URL','caption'=>'Legenda','alt'=>'Texto alternativo','address'=>'Morada'] as $field=>$label)
                            @if(array_key_exists($field,$c))<div><label class="text-xs font-bold">{{ $label }}</label>@if(in_array($field,['body','description'],true))<textarea wire:model.live.debounce.300ms="sections.{{ $sIndex }}.content.{{ $field }}" rows="4" class="mt-2 w-full rounded-xl border-zinc-200 text-sm dark:border-zinc-700 dark:bg-zinc-800"></textarea>@else<input wire:model.live.debounce.300ms="sections.{{ $sIndex }}.content.{{ $field }}" class="mt-2 w-full rounded-xl border-zinc-200 text-sm dark:border-zinc-700 dark:bg-zinc-800">@endif</div>@endif
                        @endforeach
                        @if(isset($c['items']) && is_array($c['items']))
                            <div class="border-t border-zinc-100 pt-5 dark:border-zinc-800"><div class="flex items-center justify-between"><div><p class="text-xs font-black">Itens</p><p class="mt-1 text-[10px] text-zinc-400">Adiciona e organiza conteúdos repetidos.</p></div><button type="button" wire:click="addItem({{ $sIndex }})" class="rounded-lg bg-indigo-50 px-2.5 py-1.5 text-[10px] font-bold text-indigo-700">+ Adicionar</button></div><div class="mt-3 space-y-3">@foreach($c['items'] as $itemIndex=>$item)<div class="rounded-xl border border-zinc-200 p-3 dark:border-zinc-700"><div class="flex items-center justify-between"><span class="text-[10px] font-black text-zinc-400">Item {{ $itemIndex+1 }}</span><div class="flex gap-1"><button type="button" wire:click="moveItem({{ $sIndex }},{{ $itemIndex }},'up')" class="px-1 text-xs">↑</button><button type="button" wire:click="moveItem({{ $sIndex }},{{ $itemIndex }},'down')" class="px-1 text-xs">↓</button><button type="button" wire:click="removeItem({{ $sIndex }},{{ $itemIndex }})" class="px-1 text-xs text-red-600">×</button></div></div>@foreach($item as $key=>$value)@if(!is_array($value))<label class="mt-2 block text-[10px] font-bold text-zinc-500">{{ \Illuminate\Support\Str::headline($key) }}<input wire:model.live.debounce.300ms="sections.{{ $sIndex }}.content.items.{{ $itemIndex }}.{{ $key }}" class="mt-1 w-full rounded-lg border-zinc-200 text-xs dark:border-zinc-700 dark:bg-zinc-800"></label>@endif @endforeach</div>@endforeach</div></div>
                        @endif
                        <div class="border-t border-zinc-100 pt-5 dark:border-zinc-800"><p class="text-xs font-black">Secção</p><div class="mt-3 grid grid-cols-2 gap-2"><button type="button" wire:click="moveSection({{ $sIndex }},'up')" class="rounded-lg border p-2 text-xs">↑ Subir</button><button type="button" wire:click="moveSection({{ $sIndex }},'down')" class="rounded-lg border p-2 text-xs">↓ Descer</button><button type="button" wire:click="duplicateSection({{ $sIndex }})" class="rounded-lg border p-2 text-xs">Duplicar</button><button type="button" wire:click="removeSection({{ $sIndex }})" class="rounded-lg border border-red-200 p-2 text-xs text-red-600">Eliminar</button></div></div>
                    @endif
                @endif
                <div class="border-t border-zinc-100 pt-5 dark:border-zinc-800"><p class="text-xs font-black">Design do website</p><p class="mt-1 text-[10px] leading-4 text-zinc-400">Cores e largura usadas como base visual.</p><div class="mt-3 grid grid-cols-2 gap-2">@foreach(['primary'=>'Principal','secondary'=>'Secundária','background'=>'Fundo','text'=>'Texto'] as $key=>$label)<label class="text-[10px] font-bold">{{ $label }}<input type="color" wire:model.live="theme.{{ $key }}" class="mt-1 h-9 w-full cursor-pointer rounded-lg border"></label>@endforeach</div><label class="mt-3 block text-[10px] font-bold">Largura do conteúdo<select wire:model.live="theme.content_width" class="mt-1 w-full rounded-lg border-zinc-200 text-xs dark:border-zinc-700 dark:bg-zinc-800"><option value="960px">Compacta</option><option value="1200px">Normal</option><option value="1440px">Grande</option></select></label></div>
            </div>
        </aside>
    </div>

    <div class="border-t border-zinc-200 bg-white px-3 py-2 lg:hidden dark:border-zinc-800 dark:bg-zinc-900"><div class="flex gap-2"><button type="button" @click="add=true" class="flex-1 rounded-xl bg-zinc-950 py-2 text-xs font-bold text-white">+ Adicionar</button><button type="button" @click="settings=true" class="flex-1 rounded-xl border py-2 text-xs font-bold">Personalizar</button><button type="button" wire:click="save" class="rounded-xl border px-4 py-2 text-xs font-bold">Guardar</button></div></div>