<div class="flex h-screen flex-col" x-data="{ mobile:false, tablet:false }">
    <header class="z-20 flex h-14 shrink-0 items-center justify-between border-b border-zinc-200 bg-white px-4 dark:border-zinc-800 dark:bg-zinc-900">
        <div class="flex items-center gap-3"><a href="{{ route('dashboard') }}" wire:navigate class="font-semibold tracking-tight">FINDER</a><span class="text-zinc-300">/</span><span class="max-w-48 truncate text-sm text-zinc-500">{{ $site->name }}</span></div>
        <div class="flex items-center gap-2"><span class="hidden text-xs text-zinc-400 sm:inline">{{ $dirty ? 'Alterações por guardar' : 'Guardado' }}</span><flux:button size="sm" href="{{ route('site.public', $site) }}" target="_blank">Preview</flux:button><flux:button size="sm" wire:click="save" wire:loading.attr="disabled">Guardar</flux:button><flux:button size="sm" variant="primary" wire:click="publish" wire:loading.attr="disabled">Publicar</flux:button></div>
    </header>

    <div class="flex min-h-0 flex-1">
        <aside class="hidden w-64 shrink-0 overflow-y-auto border-r border-zinc-200 bg-white p-4 lg:block dark:border-zinc-800 dark:bg-zinc-900">
            <div class="flex items-center justify-between"><p class="text-xs font-semibold uppercase tracking-wider text-zinc-400">Elementos</p></div>
            <div class="mt-3 grid grid-cols-2 gap-2">@foreach(['hero','text','image','button','feature_grid','card','testimonials','faq','gallery','contact_form','product_grid','video','newsletter','cta'] as $type)<button type="button" wire:click="addSection('{{ $type }}')" class="rounded-xl border border-zinc-200 px-2 py-3 text-left text-xs font-medium transition hover:border-indigo-300 hover:bg-indigo-50 dark:border-zinc-700 dark:hover:border-indigo-500/40 dark:hover:bg-indigo-500/10">{{ \Illuminate\Support\Str::headline($type) }}</button>@endforeach</div>
            <div class="mt-8 flex items-center justify-between"><p class="text-xs font-semibold uppercase tracking-wider text-zinc-400">Páginas</p><button wire:click="createPage" class="rounded-lg px-2 py-1 text-xs font-semibold text-indigo-600">+ Página</button></div>
            <div class="mt-3 space-y-1">@foreach($site->pages as $page)<button wire:click="selectPage({{ $page->id }})" class="flex w-full items-center justify-between rounded-lg px-3 py-2 text-left text-sm {{ $pageId === $page->id ? 'bg-indigo-50 text-indigo-700 dark:bg-indigo-500/10 dark:text-indigo-300' : 'text-zinc-600 hover:bg-zinc-100 dark:text-zinc-300 dark:hover:bg-zinc-800' }}"><span>{{ $page->name }}</span>@if($page->is_homepage)<span class="text-[10px] text-zinc-400">HOME</span>@endif</button>@endforeach</div>
            <div class="mt-3 flex gap-2"><button wire:click="duplicatePage" class="flex-1 rounded-lg border border-zinc-200 px-2 py-2 text-xs dark:border-zinc-700">Duplicar</button>@if($site->pages->count() > 1 && $site->pages->firstWhere('id',$pageId)?->is_homepage === false)<button wire:click="deletePage" class="rounded-lg border border-red-200 px-2 py-2 text-xs text-red-600 dark:border-red-900">Apagar</button>@endif</div>
        </aside>

        <main class="min-w-0 flex-1 overflow-y-auto bg-zinc-100 p-4 sm:p-6 dark:bg-zinc-950">
            <div class="mx-auto max-w-5xl">
                <div class="mb-4 flex flex-wrap items-center justify-between gap-3"><div><input wire:model.live.debounce.500ms="pageName" class="border-0 bg-transparent p-0 text-lg font-semibold outline-none focus:ring-0" aria-label="Nome da página"><p class="text-xs text-zinc-400">/{{ $pageSlug }}</p></div><div class="flex items-center gap-1 rounded-xl border border-zinc-200 bg-white p-1 dark:border-zinc-800 dark:bg-zinc-900"><button @click="mobile=false; tablet=false" class="rounded-lg px-3 py-1.5 text-xs">Desktop</button><button @click="mobile=false; tablet=true" class="rounded-lg px-3 py-1.5 text-xs">Tablet</button><button @click="mobile=true; tablet=false" class="rounded-lg px-3 py-1.5 text-xs">Mobile</button></div></div>

                <div class="mx-auto overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-xl transition-all dark:border-zinc-800" :class="mobile ? 'max-w-[390px]' : (tablet ? 'max-w-[768px]' : 'max-w-none')">
                    <div class="border-b border-zinc-100 px-6 py-4 text-xs text-zinc-400 dark:border-zinc-800">{{ $site->name }}</div>
                    <div class="space-y-0">
                        @forelse($sections as $index => $section)
                            <section class="group relative border-b border-zinc-100 p-8 last:border-0 dark:border-zinc-800" wire:key="section-{{ $section['id'] ?? 'new-'.$index }}">
                                <div class="absolute right-3 top-3 hidden items-center gap-1 rounded-lg border border-zinc-200 bg-white p-1 shadow-sm group-hover:flex dark:border-zinc-700 dark:bg-zinc-900"><button wire:click="moveSection({{ $index }}, 'up')" class="p-1.5 text-xs">↑</button><button wire:click="moveSection({{ $index }}, 'down')" class="p-1.5 text-xs">↓</button><button wire:click="removeSection({{ $index }})" class="p-1.5 text-xs text-red-600">×</button></div>
                                @if($section['type'] === 'hero')<div class="mx-auto max-w-3xl text-center"><input wire:model.live.debounce.500ms="sections.{{ $index }}.content.title" class="w-full border-0 bg-transparent text-center text-4xl font-bold tracking-tight outline-none focus:ring-0"><textarea wire:model.live.debounce.500ms="sections.{{ $index }}.content.subtitle" rows="2" class="mt-4 w-full resize-none border-0 bg-transparent text-center text-zinc-500 outline-none focus:ring-0"></textarea><input wire:model.live.debounce.500ms="sections.{{ $index }}.content.button_label" class="mt-6 rounded-xl border border-zinc-200 px-4 py-2 text-sm font-medium outline-none focus:border-indigo-500 dark:border-zinc-700"></div>
                                @elseif($section['type'] === 'text')<div class="mx-auto max-w-3xl"><input wire:model.live.debounce.500ms="sections.{{ $index }}.content.title" class="w-full border-0 bg-transparent text-2xl font-semibold outline-none focus:ring-0"><textarea wire:model.live.debounce.500ms="sections.{{ $index }}.content.body" rows="4" class="mt-3 w-full resize-none border-0 bg-transparent text-zinc-500 outline-none focus:ring-0"></textarea></div>
                                @elseif($section['type'] === 'feature_grid')<div class="mx-auto max-w-4xl"><input wire:model.live.debounce.500ms="sections.{{ $index }}.content.title" class="w-full border-0 bg-transparent text-center text-2xl font-semibold outline-none focus:ring-0"><div class="mt-6 grid gap-4 md:grid-cols-3">@foreach(($section['content']['items'] ?? []) as $itemIndex => $item)<div class="rounded-2xl border border-zinc-200 p-5 dark:border-zinc-700"><input wire:model.live.debounce.500ms="sections.{{ $index }}.content.items.{{ $itemIndex }}.title" class="w-full border-0 bg-transparent font-semibold outline-none focus:ring-0"><textarea wire:model.live.debounce.500ms="sections.{{ $index }}.content.items.{{ $itemIndex }}.description" rows="2" class="mt-2 w-full resize-none border-0 bg-transparent text-sm text-zinc-500 outline-none focus:ring-0"></textarea></div>@endforeach</div></div>
                                @elseif($section['type'] === 'cta')<div class="mx-auto max-w-2xl rounded-3xl bg-zinc-950 p-10 text-center text-white"><input wire:model.live.debounce.500ms="sections.{{ $index }}.content.title" class="w-full border-0 bg-transparent text-center text-3xl font-bold outline-none focus:ring-0"><textarea wire:model.live.debounce.500ms="sections.{{ $index }}.content.description" rows="2" class="mt-3 w-full resize-none border-0 bg-transparent text-center text-zinc-300 outline-none focus:ring-0"></textarea></div>
                                @else<div class="mx-auto max-w-3xl rounded-2xl border-2 border-dashed border-zinc-200 p-10 text-center dark:border-zinc-700"><p class="font-semibold">{{ \Illuminate\Support\Str::headline($section['type']) }}</p><p class="mt-1 text-sm text-zinc-500">Componente disponível. As propriedades específicas podem ser configuradas aqui.</p></div>@endif
                            </section>
                        @empty<div class="p-20 text-center text-sm text-zinc-500">Adiciona um elemento a partir da barra lateral.</div>@endforelse
                    </div>
                </div>
            </div>
        </main>

        <aside class="hidden w-72 shrink-0 overflow-y-auto border-l border-zinc-200 bg-white p-4 xl:block dark:border-zinc-800 dark:bg-zinc-900"><p class="text-xs font-semibold uppercase tracking-wider text-zinc-400">Tema</p><div class="mt-4 space-y-4"><label class="block text-sm">Cor principal<input type="color" wire:model.live="theme.primary" class="mt-2 block h-10 w-full cursor-pointer rounded-lg border border-zinc-200 bg-white p-1 dark:border-zinc-700"></label><label class="block text-sm">Cor secundária<input type="color" wire:model.live="theme.secondary" class="mt-2 block h-10 w-full cursor-pointer rounded-lg border border-zinc-200 bg-white p-1 dark:border-zinc-700"></label><label class="block text-sm">Fundo<input type="color" wire:model.live="theme.background" class="mt-2 block h-10 w-full cursor-pointer rounded-lg border border-zinc-200 bg-white p-1 dark:border-zinc-700"></label><label class="block text-sm">Texto<input type="color" wire:model.live="theme.text" class="mt-2 block h-10 w-full cursor-pointer rounded-lg border border-zinc-200 bg-white p-1 dark:border-zinc-700"></label><label class="block text-sm">Largura<input wire:model.live="theme.content_width" class="mt-2 w-full rounded-lg border border-zinc-200 px-3 py-2 text-sm dark:bg-zinc-800"></label></div></aside>
    </div>
</div>
