<div class="fixed bottom-24 right-6 z-40">
    @if ($open)
        <section class="mb-3 w-[min(22rem,calc(100vw-3rem))] overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-2xl">
            <header class="flex items-center justify-between bg-stone-950 px-5 py-4 text-white"><div><p class="text-xs font-semibold uppercase tracking-[0.16em] text-amber-300">Casa &amp; Co.</p><h2 class="mt-1 font-semibold">Assistente Casa &amp; Co.</h2></div><button type="button" wire:click="toggle" aria-label="Fechar assistente" class="text-xl text-stone-300 hover:text-white">&times;</button></header>
            <div class="max-h-[28rem] overflow-y-auto p-5"><p class="text-sm leading-6 text-stone-600">Diga-me o que procura e encontro sugestões disponíveis no nosso catálogo.</p><form wire:submit="ask" class="mt-4"><textarea wire:model="question" rows="2" placeholder="Ex.: Preciso de uma prenda até 30 €" class="w-full resize-none rounded-lg border-stone-300 text-sm" required></textarea>@error('question')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror<button type="submit" class="mt-2 w-full rounded-lg bg-amber-400 px-4 py-2.5 text-sm font-semibold text-stone-950 hover:bg-amber-300" wire:loading.attr="disabled">Encontrar sugestões</button></form>@if ($answer)<div class="mt-5 rounded-lg bg-amber-50 p-4"><p class="text-sm font-semibold text-stone-900">{{ $answer }}</p>@if ($suggestions->isNotEmpty())<div class="mt-3 space-y-3">@foreach ($suggestions as $product)<a href="{{ route('products.show', $product) }}" wire:navigate class="flex items-center justify-between gap-3 rounded-lg bg-white p-3 text-sm shadow-sm hover:ring-2 hover:ring-amber-300"><span class="min-w-0"><strong class="block truncate">{{ $product->name }}</strong><span class="text-xs text-stone-500">{{ $product->category?->name }}</span></span><span class="shrink-0 font-semibold">€ {{ number_format($product->price, 2, ',', '.') }}</span></a>@endforeach</div>@endif</div>@endif</div>
        </section>
    @endif
    <button type="button" wire:click="toggle" aria-label="Abrir Assistente Casa & Co." title="Assistente Casa & Co." class="flex size-16 items-center justify-center rounded-full bg-amber-400 text-2xl text-stone-950 shadow-xl ring-4 ring-white transition hover:-translate-y-1 hover:bg-amber-300">✦</button>
</div>
