<main class="store-reveal mx-auto max-w-5xl px-5 py-10 sm:px-8 lg:px-12 lg:py-14">
    @if ($section === 'overview')
        <section class="overflow-hidden rounded-2xl bg-stone-950 p-7 text-white shadow-xl sm:p-10"><div class="flex flex-col justify-between gap-8 sm:flex-row sm:items-end"><div><p class="text-sm font-semibold uppercase tracking-[0.18em] text-amber-300">Área pessoal</p><h1 class="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">A minha conta</h1><p class="mt-3 max-w-xl text-stone-300">Olá, {{ auth()->user()->name }}. Tudo o que precisa, num só lugar.</p></div><div class="flex size-16 items-center justify-center rounded-full bg-amber-300 text-xl font-bold text-stone-950">{{ auth()->user()->initials() }}</div></div></section>
        <section class="mt-5 grid gap-4 sm:grid-cols-3"><div class="rounded-xl border border-stone-200 bg-white p-5"><p class="text-sm text-stone-500">Encomendas</p><p class="mt-3 text-3xl font-semibold">{{ $orders->count() }}</p></div><div class="rounded-xl border border-stone-200 bg-white p-5"><p class="text-sm text-stone-500">Em curso</p><p class="mt-3 text-3xl font-semibold">{{ $orders->whereNotIn('status', ['entregue', 'cancelada'])->count() }}</p></div><div class="rounded-xl border border-stone-200 bg-white p-5"><p class="text-sm text-stone-500">Total comprado</p><p class="mt-3 text-3xl font-semibold">€ {{ number_format($totalSpent, 2, ',', '.') }}</p></div></section>
        <section class="mt-10 grid gap-8 lg:grid-cols-[1.15fr_0.85fr]"><div><div class="flex items-center justify-between"><h2 class="text-xl font-semibold">Atividade recente</h2><a href="{{ route('orders.tracking') }}" wire:navigate class="text-sm font-semibold text-amber-700 hover:text-amber-900">Ver todas</a></div><div class="mt-4 overflow-hidden rounded-xl border border-stone-200 bg-white">@forelse ($orders->take(3) as $order)<a href="{{ route('orders.tracking') }}" wire:navigate class="flex items-center justify-between gap-4 border-b border-stone-100 px-5 py-4 last:border-0 hover:bg-amber-50"><div class="flex min-w-0 items-center gap-3"><span class="flex size-10 shrink-0 items-center justify-center rounded-full bg-amber-100">📦</span><div class="min-w-0"><p class="truncate text-sm font-semibold">#{{ $order->order_number }}</p><p class="truncate text-xs text-stone-500">{{ $order->items->sum('quantity') }} artigo(s) · {{ $order->sold_at->format('d/m/Y') }}</p></div></div><span class="shrink-0 text-sm font-semibold">€ {{ number_format($order->total, 2, ',', '.') }}</span></a>@empty<div class="px-5 py-10 text-center"><p class="font-semibold">Ainda não tem encomendas.</p><a href="{{ route('products') }}" wire:navigate class="mt-3 inline-block text-sm font-semibold text-amber-700">Explorar produtos &rarr;</a></div>@endforelse</div></div><div><h2 class="text-xl font-semibold">Acesso rápido</h2><div class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-1"><a href="{{ route('profile.edit') }}" wire:navigate class="flex items-center justify-between rounded-xl border border-stone-200 bg-white p-4 hover:border-amber-300"><span><strong class="block text-sm">Perfil</strong><span class="text-xs text-stone-500">{{ auth()->user()->email }}</span></span><span>→</span></a><a href="{{ route('account.favorites') }}" wire:navigate class="flex items-center justify-between rounded-xl border border-stone-200 bg-white p-4 hover:border-amber-300"><span><strong class="block text-sm">Favoritos</strong><span class="text-xs text-stone-500">Produtos guardados</span></span><span>→</span></a><a href="{{ route('security.edit') }}" wire:navigate class="flex items-center justify-between rounded-xl border border-stone-200 bg-white p-4 hover:border-amber-300"><span><strong class="block text-sm">Segurança</strong><span class="text-xs text-stone-500">Palavra-passe e acesso</span></span><span>→</span></a></div></div></section>
    @else
        <div><p class="text-sm font-semibold uppercase tracking-[0.18em] text-amber-700">A minha conta</p><h1 class="mt-3 text-4xl font-semibold tracking-tight">{{ $sections[$section]['title'] }}</h1><p class="mt-3 max-w-xl text-stone-600">{{ $sections[$section]['description'] }}</p></div><section class="mt-10 rounded-2xl border border-dashed border-stone-300 bg-white px-6 py-16 text-center"><p class="text-4xl">{{ $section === 'favorites' ? '♡' : '○' }}</p><h2 class="mt-4 text-lg font-semibold text-stone-900">{{ $sections[$section]['empty'] }}</h2><p class="mt-2 text-sm text-stone-500">Continue a explorar a Casa &amp; Co. para completar a sua área pessoal.</p><a href="{{ route('products') }}" wire:navigate class="mt-6 inline-flex rounded-lg bg-stone-950 px-4 py-2.5 text-sm font-semibold text-white">Ir para a loja</a></section>
    @endif
</main>
