<main class="store-reveal mx-auto max-w-5xl px-5 py-10 sm:px-8 lg:px-12 lg:py-14">
    <div><p class="text-sm font-semibold uppercase tracking-[0.18em] text-amber-700">Área do cliente</p><h1 class="mt-3 text-4xl font-semibold tracking-tight">Tracking de encomendas</h1><p class="mt-3 max-w-xl text-stone-600">Acompanhe cada passo das suas compras, desde a criação até à entrega.</p></div>
    <section class="mt-10 space-y-5">
        @forelse ($orders as $order)
            <article class="rounded-2xl border border-stone-200 bg-white p-6 shadow-sm transition hover:-translate-y-0.5 hover:border-amber-200 hover:shadow-lg sm:p-8"><div class="flex flex-col justify-between gap-3 border-b border-stone-100 pb-5 sm:flex-row sm:items-start"><div><p class="text-xs font-semibold uppercase tracking-[0.16em] text-amber-700">Encomenda</p><h2 class="mt-1 text-xl font-semibold">#{{ $order->order_number }}</h2><p class="mt-1 text-sm text-stone-500">Criada em {{ $order->sold_at->format('d/m/Y \à\s H:i') }}</p></div><span class="text-lg font-semibold">€ {{ number_format($order->total, 2, ',', '.') }}</span></div><div class="mt-7 grid gap-5 sm:grid-cols-5"><div class="relative sm:col-span-5"><div class="absolute left-4 right-4 top-4 hidden h-0.5 bg-stone-200 sm:block"></div><div class="relative grid gap-5 sm:grid-cols-5">@foreach ([['criada', 'Encomenda criada'], ['pago', 'Pagamento confirmado'], ['em_preparacao', 'Em preparação'], ['enviado', 'Enviada'], ['entregue', 'Entregue']] as [$step, $label])<div class="flex items-center gap-3 sm:block sm:text-center"><span class="relative z-10 flex size-8 shrink-0 items-center justify-center rounded-full {{ $this->isStepComplete($order, $step) ? 'bg-emerald-600 text-white' : 'bg-stone-100 text-stone-400' }}">{{ $this->isStepComplete($order, $step) ? '✓' : '○' }}</span><span class="text-sm {{ $this->isStepComplete($order, $step) ? 'font-semibold text-stone-900' : 'text-stone-400' }} sm:mt-3 sm:block">{{ $label }}</span></div>@endforeach</div></div></div><div class="mt-7 border-t border-stone-100 pt-5 text-sm text-stone-500">{{ $order->items->sum('quantity') }} artigo(s) · Estado atual: <strong class="capitalize text-stone-800">{{ str_replace('_', ' ', $order->status === 'pendente' ? 'criada' : $order->status) }}</strong></div></article>
        @empty
            <div class="rounded-2xl border border-dashed border-stone-300 bg-white/60 px-6 py-16 text-center"><p class="font-semibold">Ainda não tem encomendas.</p><p class="mt-2 text-sm text-stone-500">Explore a loja para fazer a sua primeira compra.</p><a href="{{ route('products') }}" wire:navigate class="mt-5 inline-flex rounded-lg bg-stone-950 px-4 py-2.5 text-sm font-semibold text-white">Ir para a loja</a></div>
        @endforelse
    </section>
</main>
