<div class="space-y-6 p-6 lg:p-8">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div><p class="text-sm font-medium text-indigo-600">Loja</p><h1 class="mt-1 text-2xl font-semibold tracking-tight text-zinc-950 dark:text-white">Produtos</h1><p class="mt-1 text-sm text-zinc-500">Consulta o catálogo, pesquisa produtos e gere o teu carrinho.</p></div>
        <button type="button" wire:click="$set('cartOpen', true)" class="inline-flex items-center justify-center gap-2 rounded-xl bg-zinc-950 px-4 py-2.5 text-sm font-semibold text-white hover:bg-zinc-800 dark:bg-white dark:text-zinc-950">Carrinho <span class="rounded-full bg-white/15 px-2 py-0.5 text-xs">{{ array_sum($cart) }}</span></button>
    </div>
    <div class="grid gap-3 lg:grid-cols-[1fr_auto]">
        <input wire:model.live.debounce.300ms="search" type="search" placeholder="Pesquisar produtos..." class="w-full rounded-xl border-zinc-200 bg-white py-3 shadow-sm dark:border-zinc-800 dark:bg-zinc-900">
        <select wire:model.live="category" class="rounded-xl border-zinc-200 bg-white px-4 py-3 text-sm shadow-sm dark:border-zinc-800 dark:bg-zinc-900"><option value="">Todas as categorias</option>@foreach($categories as $item)<option value="{{ $item->slug }}">{{ $item->name }}</option>@endforeach</select>
    </div>
    <div class="grid gap-3 sm:grid-cols-3">
        <input wire:model.live="minPrice" type="number" min="0" step=".01" placeholder="Preço mínimo" class="rounded-xl border-zinc-200 bg-white dark:border-zinc-800 dark:bg-zinc-900">
        <input wire:model.live="maxPrice" type="number" min="0" step=".01" placeholder="Preço máximo" class="rounded-xl border-zinc-200 bg-white dark:border-zinc-800 dark:bg-zinc-900">
        <select wire:model.live="availability" class="rounded-xl border-zinc-200 bg-white dark:border-zinc-800 dark:bg-zinc-900"><option value="">Disponibilidade</option><option value="disponivel">Em stock</option><option value="esgotado">Esgotado</option></select>
    </div>
    <div class="flex items-center justify-between"><h2 class="font-semibold text-zinc-900 dark:text-white">Catálogo</h2><span class="text-sm text-zinc-500">{{ $products->count() }} produtos</span></div>
    <div class="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">
        @forelse($products as $product)
            <article wire:key="product-{{ $product->id }}" class="overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm dark:border-zinc-800 dark:bg-zinc-900">
                @if($product->image_url)<img src="{{ asset('storage/'.$product->image_url) }}" alt="{{ $product->name }}" class="aspect-[4/3] w-full object-cover">@else<div class="flex aspect-[4/3] items-center justify-center bg-zinc-100 text-sm text-zinc-400 dark:bg-zinc-800">Sem imagem</div>@endif
                <div class="space-y-3 p-5"><div class="flex justify-between gap-3"><div><p class="text-xs font-medium uppercase tracking-wide text-indigo-600">{{ $product->category?->name }}</p><h3 class="mt-1 font-semibold text-zinc-950 dark:text-white">{{ $product->name }}</h3></div><strong class="whitespace-nowrap">€ {{ number_format($this->salePrice($product),2,',','.') }}</strong></div><p class="line-clamp-2 text-sm text-zinc-500">{{ $product->description }}</p><div class="flex items-center justify-between gap-3"><span class="text-xs text-zinc-500">{{ $product->stock > 0 ? $product->stock.' em stock' : 'Esgotado' }}</span><button type="button" wire:click="addToCart({{ $product->id }})" @disabled($product->stock <= 0) class="rounded-lg bg-zinc-950 px-3 py-2 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40 dark:bg-white dark:text-zinc-950">Adicionar</button></div></div>
            </article>
        @empty <div class="col-span-full rounded-2xl border border-dashed border-zinc-300 bg-white p-12 text-center text-sm text-zinc-500 dark:border-zinc-700 dark:bg-zinc-900">Não foram encontrados produtos.</div>@endforelse
    </div>
    @if($cartOpen)
        <div class="fixed inset-0 z-40 bg-black/30" wire:click="$set('cartOpen', false)"></div><aside class="fixed inset-y-0 right-0 z-50 flex w-full max-w-md flex-col border-l border-zinc-200 bg-white shadow-2xl dark:border-zinc-800 dark:bg-zinc-950">
            <div class="flex items-center justify-between border-b border-zinc-200 p-5 dark:border-zinc-800"><div><p class="text-xs font-medium text-indigo-600">Pedido</p><h2 class="text-lg font-semibold">Carrinho</h2></div><button wire:click="$set('cartOpen', false)" class="text-2xl text-zinc-400">&times;</button></div>
            <div class="flex-1 overflow-y-auto p-5">@forelse($this->cartProducts as $product)<div class="flex items-center justify-between gap-4 border-b border-zinc-100 py-4 dark:border-zinc-800"><div><p class="font-medium">{{ $product->name }}</p><p class="text-sm text-zinc-500">€ {{ number_format($this->salePrice($product),2,',','.') }}</p></div><div class="flex items-center gap-2"><button wire:click="decreaseQuantity({{ $product->id }})" class="size-8 rounded-lg border">−</button><span>{{ $cart[$product->id] }}</span><button wire:click="increaseQuantity({{ $product->id }})" class="size-8 rounded-lg border">+</button></div></div>@empty<p class="py-16 text-center text-sm text-zinc-500">O carrinho está vazio.</p>@endforelse</div>
            <div class="border-t border-zinc-200 p-5 dark:border-zinc-800"><div class="mb-4 flex justify-between font-semibold"><span>Total</span><span>€ {{ number_format($this->cartTotal,2,',','.') }}</span></div><button wire:click="openCheckout" @disabled(count($cart)===0) class="w-full rounded-xl bg-indigo-600 px-4 py-3 text-sm font-semibold text-white disabled:opacity-40">Finalizar encomenda</button></div>
        </aside>
    @endif
    @if($checkoutOpen)<div class="fixed inset-0 z-[60] flex items-center justify-center bg-black/40 p-4"><div class="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl dark:bg-zinc-900"><div class="flex items-center justify-between"><h2 class="text-lg font-semibold">Finalizar encomenda</h2><button wire:click="$set('checkoutOpen', false)" class="text-2xl text-zinc-400">&times;</button></div><div class="mt-5 space-y-4"><input wire:model="customerName" placeholder="Nome" class="w-full rounded-xl border-zinc-200 dark:border-zinc-700 dark:bg-zinc-950"><input wire:model="customerEmail" type="email" placeholder="Email" class="w-full rounded-xl border-zinc-200 dark:border-zinc-700 dark:bg-zinc-950"><input wire:model="customerPhone" placeholder="Telefone" class="w-full rounded-xl border-zinc-200 dark:border-zinc-700 dark:bg-zinc-950"><textarea wire:model="deliveryAddress" placeholder="Morada de entrega" rows="3" class="w-full rounded-xl border-zinc-200 dark:border-zinc-700 dark:bg-zinc-950"></textarea><select wire:model="paymentMethod" class="w-full rounded-xl border-zinc-200 dark:border-zinc-700 dark:bg-zinc-950"><option value="mbway">MB WAY</option><option value="transferencia">Transferência bancária</option><option value="cartao">Cartão</option><option value="entrega">Pagamento na entrega</option></select><button wire:click="checkout" class="w-full rounded-xl bg-indigo-600 px-4 py-3 font-semibold text-white">Confirmar encomenda</button></div></div></div>@endif
    @if($completedOrderNumber)<div class="fixed inset-0 z-[70] flex items-center justify-center bg-black/40 p-4"><div class="w-full max-w-md rounded-2xl bg-white p-7 text-center shadow-2xl dark:bg-zinc-900"><div class="mx-auto flex size-12 items-center justify-center rounded-full bg-emerald-100 text-emerald-700">✓</div><h2 class="mt-4 text-xl font-semibold">Encomenda criada</h2><p class="mt-2 text-sm text-zinc-500">Número: <strong>{{ $completedOrderNumber }}</strong></p><button wire:click="$set('completedOrderNumber', null)" class="mt-6 rounded-xl bg-zinc-950 px-4 py-2.5 text-sm font-semibold text-white dark:bg-white dark:text-zinc-950">Fechar</button></div></div>@endif
</div>