<div class="mx-auto max-w-7xl space-y-6 p-6">
    <div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-semibold text-indigo-600">{{ $site->name }}</p><h1 class="text-3xl font-bold tracking-tight">Analytics</h1><p class="mt-1 text-sm text-zinc-500">Dados reais registados pelo website público.</p></div><select wire:model.live="days" class="rounded-xl border border-zinc-200 px-3 py-2 text-sm dark:border-zinc-700 dark:bg-zinc-900"><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option><option value="90">Últimos 90 dias</option></select></div>
    <div class="grid gap-4 md:grid-cols-2"><div class="rounded-2xl border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900"><p class="text-sm text-zinc-500">Visualizações</p><p class="mt-2 text-4xl font-bold">{{ number_format($views, 0, ',', '.') }}</p></div><div class="rounded-2xl border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900"><p class="text-sm text-zinc-500">Sessões únicas</p><p class="mt-2 text-4xl font-bold">{{ number_format($uniqueSessions, 0, ',', '.') }}</p></div></div>
    <div class="grid gap-6 lg:grid-cols-2">
        <section class="rounded-2xl border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900"><h2 class="font-semibold">Páginas mais visitadas</h2><div class="mt-4 space-y-3">@forelse($byPage as $row)<div class="flex items-center justify-between gap-4"><span class="truncate text-sm">{{ $row->page?->name ?? 'Página removida' }}</span><span class="font-semibold">{{ $row->total }}</span></div>@empty<p class="text-sm text-zinc-500">Ainda não existem visualizações.</p>@endforelse</div></section>
        <section class="rounded-2xl border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900"><h2 class="font-semibold">Dispositivos</h2><div class="mt-4 space-y-3">@forelse($byDevice as $row)<div class="flex items-center justify-between"><span class="text-sm capitalize">{{ $row->device_type ?: 'desconhecido' }}</span><span class="font-semibold">{{ $row->total }}</span></div>@empty<p class="text-sm text-zinc-500">Ainda não existem dados.</p>@endforelse</div></section>
    </div>
    <section class="rounded-2xl border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900"><h2 class="font-semibold">Evolução diária</h2><div class="mt-5 overflow-x-auto"><div class="flex min-w-max items-end gap-2" style="height:220px">@forelse($daily as $row)<div class="flex w-8 flex-col items-center justify-end gap-1" title="{{ $row->day }}: {{ $row->total }}"><div class="w-full rounded-t bg-indigo-500" style="height:{{ max(8, min(190, $row->total * 8)) }}px"></div><span class="text-[9px] text-zinc-400">{{ \Carbon\Carbon::parse($row->day)->format('d/m') }}</span></div>@empty<p class="text-sm text-zinc-500">Ainda não existem visualizações.</p>@endforelse</div></div></section>
</div>
