<div class="mx-auto max-w-7xl space-y-8 px-4 py-6 sm:px-6 lg:px-8">
    <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm font-medium uppercase tracking-[0.18em] text-amber-700">Administração</p><h1 class="mt-2 text-3xl font-semibold tracking-tight text-stone-950 dark:text-white">Utilizadores</h1><p class="mt-2 text-sm text-stone-600 dark:text-zinc-400">Consulte e mantenha as contas que utilizam a loja.</p></div></div>

    @if (session('status'))<div class="rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800" role="status">{{ session('status') }}</div>@endif
    @if (session('error'))<div class="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800" role="alert">{{ session('error') }}</div>@endif

    @if ($editingUserId)
        <form wire:submit="save" class="grid gap-5 rounded-xl border border-stone-200 bg-white p-6 shadow-sm md:grid-cols-[1fr_1fr_auto] md:items-end dark:border-zinc-700 dark:bg-zinc-800">
            <div><label for="user-name" class="block text-sm font-medium text-stone-700 dark:text-zinc-300">Nome</label><input id="user-name" wire:model="name" type="text" class="mt-2 block w-full rounded-lg border-stone-300 px-3 py-2 shadow-sm"><p class="mt-1 text-sm text-red-600">@error('name'){{ $message }}@enderror</p></div>
            <div><label for="user-email" class="block text-sm font-medium text-stone-700 dark:text-zinc-300">Email</label><input id="user-email" wire:model="email" type="email" class="mt-2 block w-full rounded-lg border-stone-300 px-3 py-2 shadow-sm"><p class="mt-1 text-sm text-red-600">@error('email'){{ $message }}@enderror</p></div>
            <div><label for="user-role" class="block text-sm font-medium text-stone-700 dark:text-zinc-300">Permissão</label><select id="user-role" wire:model="role" class="mt-2 block w-full rounded-lg border-stone-300 px-3 py-2 shadow-sm"><option value="administrador">Administrador</option><option value="gestor">Gestor</option><option value="vendedor">Vendedor</option></select></div>
            <div class="flex gap-2"><button type="submit" class="rounded-lg bg-stone-950 px-4 py-2 text-sm font-semibold text-white hover:bg-stone-700">Guardar</button><button type="button" wire:click="resetForm" class="rounded-lg border border-stone-300 px-4 py-2 text-sm font-semibold text-stone-700 hover:bg-stone-50">Cancelar</button></div>
        </form>
    @endif

    <section class="overflow-hidden rounded-xl border border-stone-200 bg-white shadow-sm dark:border-zinc-700 dark:bg-zinc-800">
        <div class="flex flex-col gap-4 border-b border-stone-200 p-5 sm:flex-row sm:items-center sm:justify-between dark:border-zinc-700"><div><h2 class="font-semibold text-stone-950 dark:text-white">Contas registadas</h2><p class="mt-1 text-sm text-stone-500">{{ $users->count() }} utilizador(es) encontrado(s)</p></div><input wire:model.live.debounce.300ms="search" type="search" placeholder="Procurar por nome ou email" class="w-full rounded-lg border-stone-300 px-3 py-2 text-sm sm:max-w-xs"></div>
        <div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="border-b border-stone-200 bg-stone-50 text-xs uppercase tracking-wide text-stone-500 dark:border-zinc-700 dark:bg-zinc-900"><tr><th class="px-5 py-3">Utilizador</th><th class="px-5 py-3">Email</th><th class="px-5 py-3">Permissão</th><th class="px-5 py-3">Registo</th><th class="px-5 py-3 text-right">Ações</th></tr></thead><tbody class="divide-y divide-stone-100 dark:divide-zinc-700">@forelse ($users as $user)<tr wire:key="user-{{ $user->id }}"><td class="px-5 py-4"><div class="flex items-center gap-3"><div class="flex size-9 items-center justify-center rounded-full bg-amber-100 text-xs font-semibold text-amber-800">{{ $user->initials() }}</div><span class="font-medium text-stone-800 dark:text-zinc-200">{{ $user->name }}</span></div></td><td class="px-5 py-4 text-stone-600 dark:text-zinc-400">{{ $user->email }}</td><td class="px-5 py-4"><span class="rounded-full bg-stone-100 px-2.5 py-1 text-xs font-medium capitalize text-stone-700">{{ $user->role }}</span></td><td class="px-5 py-4 text-stone-600 dark:text-zinc-400">{{ $user->created_at?->format('d/m/Y') }}</td><td class="px-5 py-4 text-right"><button type="button" wire:click="edit({{ $user->id }})" class="mr-3 font-medium text-stone-700 hover:text-stone-950 dark:text-zinc-300">Editar</button>@if ($user->id !== auth()->id())<button type="button" wire:click="delete({{ $user->id }})" wire:confirm="Eliminar este utilizador?" class="font-medium text-red-600 hover:text-red-800">Eliminar</button>@endif</td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-stone-500">Nenhum utilizador encontrado.</td></tr>@endforelse</tbody></table></div>
    </section>
</div>
