<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * @property-read float|null $orders_sum_total Aggregate alias generated by withSum('orders', 'total').
 * @property-read int $orders_count Aggregate alias generated by withCount('orders').
 */
class Customer extends Model
{
    protected $guarded = [];

    public function site(): BelongsTo
    {
        return $this->belongsTo(Site::class);
    }

    public function orders(): HasMany
    {
        return $this->hasMany(Order::class);
    }
}
